// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBESP-iWnXHBDCAweQayUyGX_7gcIWeYDo',
    appId: '1:658111546940:web:ede5254d8573a67926e539',
    messagingSenderId: '658111546940',
    projectId: 'health-spot-f9c15',
    authDomain: 'health-spot-f9c15.firebaseapp.com',
    storageBucket: 'health-spot-f9c15.appspot.com',
    measurementId: 'G-XP4B0TCW50',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8-T0plhNhGsGY8TkjyPNuCECol-H1DP8',
    appId: '1:658111546940:android:c8587af8b98a248926e539',
    messagingSenderId: '658111546940',
    projectId: 'health-spot-f9c15',
    storageBucket: 'health-spot-f9c15.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZzm78aI1KnZPRt05M3ley0hmaSNJ3Re8',
    appId: '1:658111546940:ios:0980c27bac4f317c26e539',
    messagingSenderId: '658111546940',
    projectId: 'health-spot-f9c15',
    storageBucket: 'health-spot-f9c15.appspot.com',
    iosClientId: '658111546940-4ho1frosca01qtdb0lialmmosi39o6oi.apps.googleusercontent.com',
    iosBundleId: 'com.example.medicalCare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZzm78aI1KnZPRt05M3ley0hmaSNJ3Re8',
    appId: '1:658111546940:ios:0980c27bac4f317c26e539',
    messagingSenderId: '658111546940',
    projectId: 'health-spot-f9c15',
    storageBucket: 'health-spot-f9c15.appspot.com',
    iosClientId: '658111546940-4ho1frosca01qtdb0lialmmosi39o6oi.apps.googleusercontent.com',
    iosBundleId: 'com.example.medicalCare',
  );
}
